#!/usr/bin/python

Import('env')

import glob

sources = glob.glob("*.png")

destination = 'abakus'
for lang in ['en']:
    for pic in sources:
        env.KDEinstall('KDEDOC', "%s/%s" % (lang, destination), pic)
